### ISSUE TITLE
middle positioned labels do not correctly work

### ISSUE THREAD

**Issue by pine3ree** [foundation/foundation-sites#12142] opened 2020-08-28 15:43 UTC
## What should happen?

The `<label>` should be centered vertically against the input element

## What happens instead?

The `<label>` element is vertically centered in its own box which is higher (42px in the example https://get.foundation/sites/docs/forms.html#label-positioning) than the input (39px). The label height changes (along with its line-height and font-size changes) make it impossible to stay centered.

## Possible Solution
```scss
.label.middle {
    padding: get-side($input-padding, 'top') 0 get-side($input-padding, 'bottom');
    line-height: ($input-font-size * unitless-calc($input-line-height))  - rem-calc(1);
}
```

## Test Case and/or Steps to Reproduce (for bugs)
https://get.foundation/sites/docs/forms.html#label-positioning
examine the label/inout heights with web-dev-tools and try changing the label font size

PS
Why is `- rem-calc(1)` used in input height calculation?
I usually add twice the border size to set the height of inputs to match button's height with same line-height, font-size, v-padding and v-border.

kind regards

**Comment by DanielRuf** [comment] 2020-08-28 15:47
Please provide a codepen for reproduction purposes.

**Comment by pine3ree** [comment] 2020-08-28 19:59
Hello @DanielRuf ,

https://codepen.io/pine3ree/pen/dyMRMrK

Labels 1,2,3 are standard foundation labels with default, and increased font-size. I added a light background to show that the label height does not match the input height

Labels 4,5,6 have the same font size of 1,2,3 respectively, but the suggested solution is applied.

**Comment by DanielRuf** [comment] 2020-08-28 20:21
Well, normally you set the values in the settings.scss using the correct variables:

https://github.com/foundation/foundation-sites/blob/develop/scss/forms/_text.scss#L23

https://github.com/foundation/foundation-sites/blob/develop/scss/forms/_text.scss#L31

https://github.com/foundation/foundation-sites/blob/develop/scss/forms/_label.scss#L15

https://github.com/foundation/foundation-sites/blob/develop/scss/forms/_label.scss#L23

Changing the values for the label does not affect the input values.

https://github.com/foundation/foundation-sites/blob/develop/scss/forms/_label.scss#L35-L40

Also your issue title does not reflect the actual issue. I've changed that.

I'm a bit confused because if you do not use the sass version and the mixins you always have to adjust the line-heights and font-sizes as needed. This is how it has always worked. Foundation Sites is still a foundation of styles which are configurable with Sass and for quick prototyping. So far I've used the mixins and font-size + line-height adjustments as needed. I see no bug / error here tbh.

**Comment by DanielRuf** [comment] 2020-08-28 20:24
> Possible Solution

I'm not sure how the `medium` class is connected to the `middle` class. And I see no `medium` class in your codepen.

I think you expect more from Foundation Sites then it covers (it does not cover all edge cases and such cases where you overwrite single values instead of generating the values using the mixins).

**Comment by pine3ree** [comment] 2020-08-28 20:28
Hello @DanielRuf , right...middle, sorry for the typo...

But you can see that even the default lable is not vertically centered. It is just a lot more centered than the not ".middle" version. To be perfectly centered the box height of the labels should be identical to the box height of the inputs.

**Comment by pine3ree** [comment] 2020-08-28 20:34
@DanielRuf ,

I've tried with `$form-label-font-size: rem-calc(20);` and I get a label almost bottom aligned. Only setting changed in build. 
kind regards.

**Comment by DanielRuf** [comment] 2020-08-28 20:34
Probably just a small regression when we merged old branches into the `develop` branch. I will check the issue with the label that is too heigh. But the proposed solution is not needed.

**Comment by DanielRuf** [comment] 2020-08-28 20:54
Hm, seems this was always like that. At least this is the same for 6.4.3 and earlier too.

I think this is the same like in https://github.com/foundation/foundation-sites/issues/11662

When you set the height to `auto` for the input it works.
I guess we have to adjust the calculation of the height value. Not sure why we had it always like this.

**Comment by DanielRuf** [comment] 2020-08-28 21:03
Hm, seems this was always like that. At least this is the same for 6.4.3 and earlier too.

I think this is the same like in https://github.com/foundation/foundation-sites/issues/11662

**Comment by DanielRuf** [comment] 2020-08-28 21:03
Hm, seems this was always like that. At least this is the same for 6.4.3 and earlier releases too.

I think this is the same like in https://github.com/foundation/foundation-sites/issues/11662

**Comment by pine3ree** [comment] 2020-08-28 21:26
@DanielRuf ,

this is how I usually achieve equal heights in forms:

https://codepen.io/pine3ree/pen/qBZjNzG

(only a few basic input examples here)

**Comment by DanielRuf** [comment] 2020-08-28 22:12
See https://github.com/foundation/foundation-sites/pull/12143

Everything else out of our Foundation Sites styleguide may require custom styles as it was always the case.

**Comment by pine3ree** [comment] 2020-08-29 11:16
Hello @DanielRuf,

I don't believe https://github.com/foundation/foundation-sites/pull/12143 will completely solve the issue.

Using `$global-line-height` (decimal or %) for labels will result in a total label height still depending on the label font-size. What we actually need is to have the label height identical to the input height. There are 2 ways to achieve that:
1. setting zero vertical padding and giving the label the same height of inputs (this will work just fine for symmetrical vertical padding)
2. use the method I suggested above: use the same absolute (i.e. rem/px, not decimal, % or em) vertical padding and absolute line-height of the inputs.

kind regards.

**Comment by DanielRuf** [comment] 2020-08-29 11:35
> What we actually need is to have the label height identical to the input height.

No, I don't think so. Labels can and should grow. Same for this case. It is just basically aligned from the top. Setting the height would be a breaking change and introduce other issues.

>  setting zero vertical padding and giving the label the same height of inputs (this will work just fine for symmetrical vertical padding)

This will not work with multiline labels.

>  absolute (i.e. rem/px, not decimal, % or em) vertical padding and absolute line-height of the inputs

The paddings already use rem. It is 9 * 2 px for the label and 8 * 2 + the border for the input.

<img width="660" alt="Bildschirmfoto 2020-08-29 um 13 31 55" src="https://user-images.githubusercontent.com/827205/91635857-19acb200-e9fc-11ea-9080-0058255de6aa.png">


> Using `$global-line-height` (decimal or %) for labels will result in a total label height still depending on the label font-size.

This is correct imho. This was also the case before (1.8 as labels should have more space / higher line heights than inputs) but for aligning it with the input it has to be 1.5 - the same for the input.

Regarding same / other font-sizes (in Foundation we set label = input - 2px, this is how it is defined in our styleguides), you can and should apply custom styles in your project as previously explained.

Foundation Sites is a framework that applies a specific style and rules. If you want to modify it and this is not a normal use case like yours, apply custom styles.

**Comment by DanielRuf** [comment] 2020-08-29 11:45
As far as I can see your change introduces some side effects like issues when you increase the label font size which will not apply the correct line height. line height values should be numeric to react to the elements font size, not the root font size. This is not correct imho.

<img width="616" alt="Bildschirmfoto 2020-08-29 um 13 45 11" src="https://user-images.githubusercontent.com/827205/91636052-ed923080-e9fd-11ea-887b-e9ef81e8f283.png">

<img width="596" alt="Bildschirmfoto 2020-08-29 um 13 45 25" src="https://user-images.githubusercontent.com/827205/91636054-f08d2100-e9fd-11ea-916e-2e077c7c6d4c.png">

**Closed** 2021-08-24 23:21 UTC
Labels: scss, Label
