### ISSUE TITLE
download.get.foundation/sites/download/ 502 Bad Gateway

### ISSUE THREAD

**Issue by llucps** [foundation/foundation-sites#12188] opened 2020-12-28 15:13 UTC
I was going to download a custom foundation and it seems the URL https://download.get.foundation/sites/download/ is broken? Or is it me?

Thanks

**Comment by rahiyansafz** [comment] 2020-12-29 18:53
also facing the same problem

**Comment by DanielRuf** [comment] 2021-01-01 20:29
Closing as duplicate of https://github.com/foundation/foundation-sites/issues/12189

**Closed by DanielRuf** 2021-01-01 20:29 UTC
