### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function with BUILD

### ISSUE THREAD

**Issue by kevinmu17** [foundation/foundation-sites#11882] opened 2019-10-23 11:55 UTC
I'm getting this error when using the foundation-explicit-pieces.js and customize it to my needs.
But ONLY when i use foundation build. With foundation watch everything works just fine.

It doesnt matter which lib i turn off or on, tested with everything off and only left
`import { Foundation } from 'foundation-sites/js/foundation.core';` this works fine, but when i turn on 
`import { OffCanvas } from 'foundation-sites/js/foundation.offcanvas';` it gives me the error when using build.

## What should happen?
It should build without any errors
...

## What happens instead?
Receiving this error: **Uncaught TypeError: Super expression must either be null or a function**
...

## Possible Solution
...

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Foundation new
2. Select Zurb template
3. Open app.js
4. Uncomment `import './lib/foundation-explicit-pieces';`
5. Comment out `require('foundation-sites');`
6. Open foundation-explicit-pieces.js and comment out some imports
7. Run command **foundation build**

## Context
This error stops running any of the javascript following `$(document).foundation();`
...

## Your Environment
- Foundation version(s) used: Foundation CLI 2.2.5 & foundation-sites: ^6.5.1
- Browser(s) name and version(s): Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Device, Operating System and version: iMac macOS High Sierra version 10.13.6
- Node version: v10.15.0
- NPM version: 6.10.3

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-10-23 14:13
Hi @kevinmu17,

Please check if this is your case:

https://foundation.zurb.com/forum/posts/53700-super-expression-must-either-be-null-or-a-function-not-undefined (last response).

**Comment by kevinmu17** [comment] 2019-10-23 14:22
Hi @DanielRuf,
Thanks for the fast response!

Allready found that thread, no success.

I have
`
import { Foundation } from 'foundation-sites/js/foundation.core';
import { SmoothScroll } from 'foundation-sites/js/foundation.smoothScroll';
`

which have to work according to the docs: https://foundation.zurb.com/sites/docs/smooth-scroll.html#javascript-reference and the last response of the link you supplied.

It does work when running **foundation watch** but when i run **foundation build** en upload it to a domain I get this error

**Comment by DanielRuf** [comment] 2019-10-23 17:19
Can you creare a small repo with this setup so we can check that?

**Comment by DanielRuf** [comment] 2019-10-23 17:19
Can you create a small repo with this setup so we can check that?

**Comment by DanielRuf** [comment] 2019-10-26 20:04
I have tried it with yarn and I do not get such an error when I run `yarn build` in your repository.

**Comment by DanielRuf** [comment] 2019-10-26 20:05
Also core.tuils, util.box and a few more have to be loaded as these are hard dependencies.

**Comment by DanielRuf** [comment] 2019-10-26 20:16
Closing as I can not really reproduce it with the provided information (no details about NodeJS and Yarn version).

**Comment by DanielRuf** [comment] 2019-10-26 20:17
Feel free to provide more information with which we can reproduce this.

**Comment by kevinmu17** [comment] 2019-10-29 07:57
I don't have Yarn installed, i'm using NPM. When you look at the package.json you see that if you run `foundation build` it is running the script `"build": "gulp build --production"`

**Comment by kevinmu17** [comment] 2019-10-29 08:36
> Also core.tuils, util.box and a few more have to be loaded as these are hard dependencies.

Last month I launched a site with the exact same foundation-explicit-pieces.js as this repo without any issues... So i would say this is not true?

**Comment by DanielRuf** [comment] 2019-10-29 09:02
The installation does not work with npm because of the lockkfile.

See:

![image](https://user-images.githubusercontent.com/827205/67752402-36bad200-fa33-11e9-9c27-609b6b23db8f.png)

**Comment by DanielRuf** [comment] 2019-10-29 09:02
The installation does not work with npm because of the lockfile.

See:

![image](https://user-images.githubusercontent.com/827205/67752402-36bad200-fa33-11e9-9c27-609b6b23db8f.png)

**Comment by kevinmu17** [comment] 2019-10-29 09:08
https://github.com/foundation/foundation-cli/issues/115 Thats because of har-validator doesn't exist anymore :)

You should delete the lock file and run npm install again

**Comment by DanielRuf** [comment] 2019-10-29 09:12
Seems when I delete the packaghe-lock.json file, use `npm i && npm run build` it happens. So this is likely a bug in a dependency or with npm.

**Comment by DanielRuf** [comment] 2019-10-29 09:13
> [foundation/foundation-cli#115](https://github.com/foundation/foundation-cli/issues/115) Thats because of har-validator doesn't exist anymore :)

It does exist but not that exact version ;-)

**Comment by DanielRuf** [comment] 2019-10-29 09:13
> You should delete the lock file and run npm install again

I did not see this information in your steps to reproduce.

**Comment by DanielRuf** [comment] 2019-10-29 09:13
> You should delete the lock file and run npm install again

I did not see this information in your steps to reproduce or reproducible testcase.

**Comment by kevinmu17** [comment] 2019-10-29 09:33
> I did not see this information in your steps to reproduce or reproducible testcase.

Because this is not what i get when I run build so thats weird... The testcase steps above are correct and should not throw the har-validator error.

**Comment by DanielRuf** [comment] 2019-10-29 09:52
Please try the following:

`npm install gulp-terser --save-dev`

And change `$.uglify()` to `$.terser()` in gulpfile.babel.js.

**Comment by DanielRuf** [comment] 2019-10-29 09:53
> Because this is not what i get when I run build so thats weird... The testcase steps above are correct and should not throw the har-validator error.

Depends on the npm version and other things. You did not provide the needed information like the node and npm version.

**Comment by kevinmu17** [comment] 2019-10-30 08:53
@DanielRuf This fixes the issue indeed, but the javascript looks way different in the build (comments still preserved)

Does this mean it's a bug in uglify?? 
According to: https://blog.logrocket.com/uglify-vs-babel-minify-vs-terser-a-mini-battle-royale/
Terser is better in performance, is this something to update in the foundation cli with a PR??

**Comment by DanielRuf** [comment] 2019-10-30 09:06
> Does this mean it's a bug in uglify??

Yes, this is a bug / regression in uglifyjs with some of its dependencies.
We are moving to terser for all projects. Especially because terser fully supports current ES versions while uglifyjs does not (even ES6 as there are many issues).

**Comment by DanielRuf** [comment] 2019-10-30 09:07
In general the CLI only clones the Git repository, in this case https://github.com/foundation/foundation-zurb-template

See https://github.com/foundation/foundation-zurb-template/pull/97

**Comment by DanielRuf** [comment] 2019-11-18 05:37
> (comments still preserved)

This should normally not be the case.

**Closed** 2019-11-23 21:54 UTC
Labels: PR open, javascript, 🐛bug

**Comment by joeworkman** [comment] 2020-03-12 17:22
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/gulpfile-compiling-app-js-incorrectly-with-bloated-code/1656/14
