### ISSUE TITLE
Accordion Deep Linking scrolls to top of accordion when using smudge

### ISSUE THREAD

**Issue by audave** [foundation/foundation-sites#12355] opened 2021-12-22 23:09 UTC
This is a duplicate of closed issue https://github.com/foundation/foundation-sites/issues/12141

### What should happen?
The window should scroll down to the accordion list item identified in the hash.

### What happens instead?
It scrolls down only to the top of the entire accordion.

### Possible Solution:
This is a badly pasted patch file. Change line 104 in js/foundation.accordion.js to 
var offset = this.$element.find(`[href$="${anchor}"]`).offset();

``
diff --git a/node_modules/foundation-sites/js/foundation.accordion.js b/node_modules/foundation-sites/js/foundation.accordion.js
index 0b9096e..2cdd3dd 100644
--- a/node_modules/foundation-sites/js/foundation.accordion.js
+++ b/node_modules/foundation-sites/js/foundation.accordion.js
@@ -101,7 +101,7 @@ class Accordion extends Plugin {
         // Roll up a little to show the titles
         if (this.options.deepLinkSmudge) {
           onLoad($(window), () => {
-            var offset = this.$element.offset();
+            var offset = this.$element.find(`[href$="${anchor}"]`).offset();
             $('html, body').animate({ scrollTop: offset.top - this.options.deepLinkSmudgeOffset }, this.options.deepLinkSmudgeDelay);
           });
         }

``

### How to reproduce:

Paste the doc example deep linked accordion onto a page with basic smudge options enabled.
Add a bunch more list items so that there is room to scroll (and maybe put stuff above the accordion so that if it wants to scroll to the top of the accordion, it has room to move)
Open a list item so that you can copy the url
Navigate away and then paste the url with the deep linked hash into the url bar and press enter
Behold as it scrolls to the top of the accordion rather than down to a list item.

### Example page with error.
The following link to the same place
https://get.foundation/sites/docs/accordion.html#deeplink1
https://get.foundation/sites/docs/accordion.html#deeplink3

**Comment by denisahac** [comment] 2022-02-22 10:25
Duplicate of #12141 

@audave can you submit a PR?

**Closed** 2024-09-27 17:56 UTC
