### ISSUE TITLE
[Flexbox Mode] ISSUE NAME HERE

### ISSUE THREAD

**Issue by fernych** [foundation/foundation-sites#12187] opened 2020-12-25 14:07 UTC
## Expected Behavior

...

## Current Behavior

link to https://download.get.foundation/sites/download doesn't work. Show the 502 Bad Gateway
nginx 
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2021-01-01 20:33
Closing as duplicate of https://github.com/foundation/foundation-sites/issues/12189

Please set a relevant title next time.

**Closed by DanielRuf** 2021-01-01 20:33 UTC
