### ISSUE TITLE
[Orbit] Disappears when changing window widths on desktop

### ISSUE THREAD

**Issue by blynnc** [foundation/foundation-sites#10069] opened 2017-05-24 00:24 UTC
#### How to reproduce this bug:

ORBIT GOES INTO ORBIT : Disappears when changing window widths on desktop

1. row with two  6 column on desktop - as stated above
2. orbit slide show in the right column
3. Pulling browser window narrower then wider two or three times the Orbit slide show finally disappears on pulling window wider

#### Test case link:

Can not do that just yet. 

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by blynnc** [comment] 2017-05-24 03:39
More info.

Testing with the Custom Build with everything checked including the Motion UI CSS.
Not using SASS but CSS for now.

**Comment by blynnc** [comment] 2017-05-24 03:44
Yet More Info - Browser: Firefox 53.0.3

**Comment by kball** [comment] 2017-05-24 16:48
@blynnc are you able to put up a codepen example, send a link to the site, or give access to a repo showing the problem?

**Comment by blynnc** [comment] 2017-05-24 21:26
I'll put up some screen shots. Site under development.

**Comment by agoradesign** [comment] 2017-05-26 07:27
Sounds like https://github.com/zurb/foundation-sites/issues/9788

There you'll find the following proposal to fix the problem: https://github.com/dwt47/foundation-sites/commit/d3605d96ca410e3001447d5a3fab544556668e5e

I have already tried that in one of our projects. It seems to work. I couldn't trigger that problem anymore. And I haven't heard complaints so far - however that site is still not published, so only a few people (content editors) are actually using the site

**Comment by blynnc** [comment] 2017-05-29 18:39
It's definetly happening using both Flex and the CSS version.
With 2 columns pulling desktop window wider and then narrower a few times - The slides in orbit disappear. Also just leaving the slideshow running - after several loops - the slides disappear.

I've been tied up with a few things --- I'll post an example at end of next week.

**Comment by agoradesign** [comment] 2017-07-05 13:20
btw, this bug still exists in 6.4.1

+1 for committing the fix I've linked in a previous comment. I've used this already in a few projects now, with both 6.3.x and 6.4.x - this seems to really solve the problem. I haven't seen this bug anymore, and I haven't experienced any negative side effects

**Comment by kball** [comment] 2017-07-05 22:04
@agoradesign thanks for following up - that fix is in a PR here https://github.com/zurb/foundation-sites/pull/9881 and I was concerned it might not be the right answer, but given the original submitter has not responded to qs and feedback, and that you're reporting no issues or side effects, will go ahead and merge that for now.

**Comment by agoradesign** [comment] 2017-07-06 05:56
@kball thank you very much! I can't judge whether or not that is the rigth answer. And not seeing any issues doesn't mean that there aren't ones. But at least, and that's for sure, it's work way better this way! Because honestly without that, Orbit was more or less useless atm. Having no transitions looks a bit cheap, and turning it on caused problems...

Great to see this in now, and btw thanks for the great 6.4.x updates in general :)

**Comment by Cethy** [comment] 2017-09-06 15:21
Just stumble across this very problem, the fix seemed only to "delay" the problem (can resize the window a lot more before the problem arise).

From my "research", whenever the orbit is reset, it should `restart` its internal timer but it does not seem to do it correctly. So whenever "2" timer tries to move a slide, it does weird things and it stop working.
I couldn't find the origin of the problem but use this unoptimized solution :
In `function _reset()` :
```
// Restart timer if autoPlay is enabled
        if (this.options.autoPlay) {
          //this.timer.restart();
          this.timer = new __WEBPACK_IMPORTED_MODULE_3__foundation_util_timer__["a" /* Timer */](this.$element, {
            duration: this.options.timerDelay,
            infinite: false
          }, function () {
            _this.changeSlide(true);
          });
        }
```

Hope it helps.

Tests done on osX & chrome 61.0.3163.79 with foundation 6.4.0

**Comment by tmartin2089** [comment] 2017-09-20 18:23
Still broken in 6.4.3, the fix does delay as @Cethy commented, but you can quickly replicate it on iOS/Safari.

Anyone with a pressing deadline, `data-use-m-u-i="false"` fixes things, but you lose those smooth like butter transitions.

**Comment by DanielRuf** [comment] 2017-11-24 18:36
Would be also great to backport it to 6.3. Hosting a modified version just of the feels not ok in node projects.

**Comment by chunkitdesign** [comment] 2017-12-05 14:32
yeah still broken in the latest foundation 6.4.3. the only solution is to disable the animation

**Comment by DanielRuf** [comment] 2017-12-05 14:36
We switched in our projects from Orbit to Swiper https://danielruf.github.io/swiper-builder/

**Comment by DanielRuf** [comment] 2018-03-05 06:35
Will check this again in a few days.

**Comment by DanielRuf** [comment] 2019-10-19 16:38
I think we already fixed this in the latest releases.

We are closing this issue as we did not receive any further feedback and we do not have a codepen as reproducible testcase.

**Closed by DanielRuf** 2019-10-19 16:38 UTC
Labels: Orbit
