### ISSUE TITLE
Keyboard nav in dropdown menus broken in 6.4 RC

### ISSUE THREAD

**Issue by kball** [foundation/foundation-sites#10129] opened 2017-06-03 20:44 UTC
Attempting to use keyboard nav in the dropdown menus in the visual test /dropdown-menu/left-aligned-dropdown-menu-inside-top-bar-right.html is missing the first item, appears to be unable to find it.

Possibly related, we currently have 3 failing javascript tests associated with dropdown menus.

@Owlbertz can you take a look? Thanks

**Comment by Owlbertz** [comment] 2017-06-04 16:02
@kball, the issue is caused by the fact that the first link has no `href`-attribute and thus is not focus-able. We would either need to force a `href="#"` or to go with using `tabindex`  I guess.

**Comment by kball** [comment] 2017-06-05 18:16
OK... we can prob enforce/require the href... can you see if the failing dropdown menu JS tests are related?

**Comment by Owlbertz** [comment] 2017-06-06 07:38
Well as far as I can see the tests use a template that has a `href` present for each link, so it is probably another issue.

**Comment by DanielRuf** [comment] 2018-03-10 22:01
The tests should be fine now. Does the initial issue still exist / occur?

**Comment by DanielRuf** [comment] 2018-03-23 06:14
The visual test still has the anchor without href or tabindex. Should we use `href="#"` like in the docs or add `tabindex="0"`?

In the real world there is no anchor in a nav without a href or tabindex.

**Comment by DanielRuf** [comment] 2019-10-19 16:38
Closing as we did not receive any further feedback and the initial issue should be resolved.

**Closed by DanielRuf** 2019-10-19 16:38 UTC
Labels: 6.4 release candidate, Dropdown Menu, 🐛bug
