### ISSUE TITLE
foundation kits list from terminal not working and throw fetching file kits.json file. 

### ISSUE THREAD

**Issue by rlodhiya** [foundation/foundation-sites#12022] opened 2020-03-20 21:41 UTC
## What should happen?
foundation kits list should show a list of kits available. 
...

## What happens instead?
error fetching file /building-blocks/data/kits.json
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\Ravi Lodhiya\AppData\Roaming\npm\node_modules\foundation-cli\lib\commands\kits.js:41:21
    at IncomingMessage.<anonymous> (C:\Users\Ravi Lodhiya\AppData\Roaming\npm\node_modules\foundation-cli\lib\util\fetch-url.js:21:9)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
...

## Possible Solution

\foundation-cli\lib\commands\kits.js line number 40
should be corrected as below
fetchUrl('get.foundation', '/building-blocks/data/kits.json', function(kitJson) {
...
## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: v2.2.5
- Browser(s) name and version(s): 
- Device, Operating System and version: Windows 10 Pro 64 bit
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2020-03-21 11:56
Hi @rlodhiya,

thanks for reporting this.

We are aware of this. Please see https://github.com/foundation/foundation-cli/commit/0cd91f0cb19c3101f7dbad7d33ca7d5ddd873a2f and change the files in your foundation-cli.

Duplicate of https://github.com/foundation/foundation-cli/issues/122

**Closed by DanielRuf** 2020-03-21 11:56 UTC
