### ISSUE TITLE
BrowserSync and Sticky not working together

### ISSUE THREAD

**Issue by nolafs** [foundation/foundation-sites#12051] opened 2020-04-12 15:08 UTC
## What should happen?

It seems using BrowserSync and Foundation Sticky aren't working together. For hours I was trying to work out why my title-bar keeps sticking to the bottom of the page instead to the top. Then I ran a production build and the code worked perfectly fine. Wasted hours. Anybody experience the same issue, any fixes as it seems you cannot trust the version viewed with browsersync.

## What happens instead?

Site should look and behave identical to the production build. 

## Possible Solution

No solution

**Comment by DanielRuf** [comment] 2020-04-12 15:46
Hi @nolafs,

what exact version of Foundation Sites do you use?

Generally BrowserSync is for development and not for production websites.
Also please make sure that you wrap `$(document).foundation()` in the documentready check of jQuery.

**Comment by nolafs** [comment] 2020-04-12 15:50
Hi,

yes, the production build works but during development it does not which makes the development impossible. It moves the sticky title-bar to the bottom of the page.

"browser-sync": "~2.24.7",
 "foundation-sites": "~6.6.3",
 "jquery": "^3.3.1"

Cheers
Olaf

**Comment by DanielRuf** [comment] 2020-04-12 16:50
Does this also occur when you reload the page?
How did you initialize Foundation Sites?

Please provide a small example project as reproducible testcase so we can see it there.

**Comment by nolafs** [comment] 2020-04-13 11:01
Hi Daniel,

Thanks for getting back to me. I am afraid it is not so easy. My se setup is Lando + Bedrock Wordpress and Sage 9. I have experience the same issue with other projects but presumed something in my own CSS causing the issue. Ended up  implemented my own sticky navigation. This time I was determined to actually make work. Tested it my code in codePen, it all worked fine. Soon I used the code in my development stuck, the margin top is set to the height of the page. Only through luck, it is working on production build.

```
<header>
  <div data-sticky-container >
    <div class="top-header" data-sticky  data-options="anchor: page, marginTop: 0;">
<div class="title-bar top-desktop">
              <div class=" title-bar-left">
                @include('partials.logo')
              </div>
              <div class="title-bar-right text-right">
                <ul class="dropdown menu align-center" data-dropdown-menu data-alignment="right" data-closing-time="200">
                  @if (has_nav_menu('primary_navigation'))
                    {!!wp_nav_menu($primarymenu);  !!}
                  @endIf
                </ul>
            </div>
      </div>
    </div>
  </div>
</header>
```

**Comment by DanielRuf** [comment] 2020-04-13 11:17
Do you use jQuery.ready / wait until everything is loaded and load the js directly before `</body>`?

**Comment by nolafs** [comment] 2020-04-13 11:29
yes, but I do think you are on to something. The injection of the main.js is in the header during development. The script to init foundation is correct a you see below.

```
import 'foundation-sites/js/entries/foundation'
import 'foundation-sites/js/entries/foundation-plugins'

jQuery(document).ready($ => ($(document).foundation()));
```

When run $(document).foundation() & $(document).resize(), the navigation position correctly. So perhaps, the main.js injection needs to be at bottom.

**Comment by nolafs** [comment] 2020-04-13 11:37
ok, to fix this behaviour temporary. I run the following after the first init.

```
  setTimeout(() => {
      $(document).foundation();
      $(document).resize();
    }, 500);
```

That moves the bar into the right position when using development setup.

**Comment by DanielRuf** [comment] 2020-04-13 12:32
js files should never be loaded in `<head>`, this is the problem. Please move all js files after the content right before `</body>`.

Your timeout "racecondition" workaround is not a real solution as it delays the execution of js by 500ms but this can take longer depending on the internet connection and client performance.

**Comment by DanielRuf** [comment] 2020-04-13 12:35
You may also want to split your main.js file into the foundation + foundation-plugins part and a separate script.js file which contains everything below the two imports (if your setup can do this).

Normally there should be chunks and emitted files for the library and its dependencies (do not bundle) and one for your code.

**Comment by nolafs** [comment] 2020-04-13 12:39
yes, I am aware of this and production does position correctly, hence it works. It is browsersync which positions it for development into the header. 

I believe this is less of a Foundation issue than it is Sage 9.  The fix above is only for me to get it working on my dev.

**Comment by DanielRuf** [comment] 2020-04-13 12:41
Ok I think we can close this as resolved now as this is not a bug on our end and you found a solution that works for you.

**Closed** 2020-04-13 12:43 UTC
