### ISSUE TITLE
Dropdown menu reopens on mobile devices (devices with touch).

### ISSUE THREAD

**Issue by rafalkaczmarek** [foundation/foundation-sites#11267] opened 2018-05-15 08:40 UTC
## What should happen?
Dropdown menu should close after touch/click on link on mobile devices.

## What happens instead?
Dropdown menu reopen after touch on link on mobile devices.

## Possible Solution
change inside foundation.dropdownMenu.js

change this

```
    if (this.options.clickOpen || hasTouch) {
      this.$menuItems.on('click.zf.dropdownMenu touchstart.zf.dropdownMenu', handleClickFn);
    }
```
to this
```
    if (this.options.clickOpen) {
      this.$menuItems.on('click.zf.dropdownMenu', handleClickFn);
    }
    if (hasTouch) {
      this.$menuItems.on('touchstart.zf.dropdownMenu', handleClickFn);
    }
```

## Test Case and/or Steps to Reproduce
How to reproduce:
1) go to foundation kitchen sink on mobile device (any device with touch or chrome developers with responsive device)
2) everythink works fine until you refresh page, after refresh dropdown menu reopens on click on the menu link

## Context
I need to dynamic build menu, when something changes I need to rebuild/refresh menu. It is not working on mobile devices.

## Your Environment
- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): All with touch
- Operating System and version (desktop or mobile): Windows 10, Androind 7, Ipad

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.
![2018-05-15_10h37_17](https://user-images.githubusercontent.com/6103873/40046064-46cd8ae8-582c-11e8-9e3c-293f53ee17bb.gif)

**Comment by rafalkaczmarek** [comment] 2018-05-15 09:06
I think that the possible solution is not working unfortunate :(.

**Comment by DanielRuf** [comment] 2020-04-29 19:11
I'm failing to see how this resolves the issue. Also I think this is a duplicate of https://github.com/foundation/foundation-sites/issues/10730

See also https://github.com/foundation/foundation-sites/issues/11423 and https://github.com/foundation/foundation-sites/pull/11430

**Closed by DanielRuf** 2020-04-29 19:11 UTC
Labels: Dropdown, javascript
