### ISSUE TITLE
[Installation] DOWNLOAD ZIP

### ISSUE THREAD

**Issue by allanfoppa** [foundation/foundation-sites#12192] opened 2021-01-06 11:43 UTC
The link https://download.get.foundation/sites/download is broken

**Comment by DanielRuf** [comment] 2021-01-07 10:44
Duplicate of this pinned issue: https://github.com/foundation/foundation-sites/issues/12189

Please use the search before opening a new issue.

**Comment by DanielRuf** [comment] 2021-01-07 10:45
cc @joeworkman please let me know if you need help with the setup.

**Closed by DanielRuf** 2021-01-07 10:44 UTC
