### ISSUE TITLE
[Dropdown Menu] Dropdown menu getting overflow in the page

### ISSUE THREAD

**Issue by Aravin** [foundation/foundation-sites#11417] opened 2018-07-23 07:26 UTC
## Expected Behavior
Content should not overflow in dropdown menu.

## Current Behavior

![image](https://user-images.githubusercontent.com/4869265/43062739-6e27d48c-8e77-11e8-9adc-d46e4f4b4acf.png)
                                             

How to reproduce (Code):

Option 1:
```
<button class="button float-left" type="button" data-toggle="example-dropdown">
                <i class="fa fa-ellipsis-v"></i>
              </button>
              <div class="dropdown-pane" data-position="bottom" data-alignment="center" id="example-dropdown" data-dropdown data-auto-focus="true">
                <ul class="dropdown menu">
                  <li><button class="button"> Item 1</button></li>
                  <li><button class="button"> Item 2</button></li>
                  <li><button class="button"> Item 3</button></li>
                </ul>
              </div>
```

Option 2

```
<ul class="dropdown menu" data-dropdown-menu>
                <li class="">
                  <a href="#Item-2" class=""></i></a>
                  <ul class="menu float-left">
                    <li><a class="" href="#Item-2A">Item 2A</a></li>
                    <li><a class="" href="#Item-2B">Item 2B</a></li>
                  </ul>
                </li>
              </ul>
```                                       

## Your Environment

- Foundation version(s) used: 6.4.x
- Browser(s) name and version(s): Chrome
- Operating System and version (desktop or mobile): Windows - Web
- Link to your project:

**Comment by ncoden** [comment] 2018-08-02 21:57
Hi @Aravin!

I am not sure of the behavior you expected, but in all cases this is not a bug:
- If you want the Dropdown to be displayed over or outside of the scrolling section, I am afraid that there is no way to do that and that you should avoid using floating elements in that case.
- If you want the Dropdown to be displayed correctly inside the scrolling section without overflowing, you can use the `data-parent-class` option to make the Dropdown positioning itself within the section limits. See https://foundation.zurb.com/sites/docs/dropdown.html#js-options.

Otherwise, please give more details about what you expected and provide a CodePen so we can reproduce your bug.

**Comment by Aravin** [comment] 2018-08-03 16:59
Bro,

Actually, it is not scrolling section.

When I hover it become scrolling and some content goes outside the display area.

Also `data-parent-class` doesn't works.

**Comment by ncoden** [comment] 2018-08-03 20:41
@Aravin thank you for the explainaitions. I am not able to reproduce it. Could you provide a Codepen showing the issue ? Thank you.

**Comment by DanielRuf** [comment] 2019-11-18 05:57
Closing as we did not receive further feedback.

**Closed by DanielRuf** 2019-11-18 05:57 UTC
Labels: Dropdown Menu, information needed
