### ISSUE TITLE
[Tooltip] Tooltip not working in Foundation v6.6.0 

### ISSUE THREAD

**Issue by AScottJohnson** [foundation/foundation-sites#11930] opened 2019-12-09 19:06 UTC
## What should happen?

When mousing over the tooltip text, the tooltip window should appear above the text.

![image](https://user-images.githubusercontent.com/1343221/70464157-2c004d80-1a73-11ea-9888-f72e88ab32ef.png)

## What happens instead?

The tooltip window doesn't display.

![image](https://user-images.githubusercontent.com/1343221/70464110-1be86e00-1a73-11ea-99e4-48add670ceb3.png)

## Test Case

Using Foundation v6.6.0 (tooltip not working): https://codepen.io/scottjohnson/pen/d0102353bf09e673801f1c4949f4430a?editors=1010

Same as above, but using v6.5.3 (tooltip working): https://codepen.io/scottjohnson/pen/b56c932034f510bf13cd5c671a6d8ddc?editors=1010

## Your Environment

macOS Catalina (10.15.1):
- Firefox 71.0
- Chrome 78.0.3904.108
- Safari 13.0.3

Windows 10 (BrowserStack):
- Edge 18

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by arjendejong12** [comment] 2019-12-09 22:22
Fwiw, both codepens are working for me correctly on Chrome 80 on Android 10.

**Comment by DanielRuf** [comment] 2019-12-09 22:42
Currently bisecting this.

**Comment by DanielRuf** [comment] 2019-12-09 23:58
3fb505600fa8e61e7ef76c5f6b8b999650f99192 is the cause.

This is fixed by https://github.com/foundation/foundation-sites/pull/11925

**Comment by arjendejong12** [comment] 2019-12-10 10:02
Could a new version (6.6.1) be released for this fix? It's a pretty serious problem if not having this fix breaks sticky and tooltips.

**Comment by arjendejong12** [comment] 2019-12-13 20:46
@joeworkman Thanks for the new 6.6.1 release!

**Closed** 2019-12-13 21:00 UTC
Labels: Tooltip, javascript
