### ISSUE TITLE
SCSS breakpoint mixins can break if a custom breakpoint is added in settings file

### ISSUE THREAD

**Issue by MildTomato** [foundation/foundation-sites#11960] opened 2020-01-08 14:59 UTC
## What should happen?

By adding a new 'custom' breakpoint in scss settings, you can then use the new breakpoint instead of using the foundation defaults.

So, add the following in settings.scss

```
$breakpoints: (
  small: 0,
  medium: 640px,
  newbreakpoint: 800px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px
);
```
we've added a breakpoint called 'newbreakpoint', which has a value of 800px, so we add it below medium, so they are in order of value.

If we use the following mixin in scss like so like this 

```
.my-class {
 @include breakpoint(medium down) {
  margin: 16px;
 }
}
```

then the changes to any element with `.my-class` should take affect once the browser hits 640px 

## What happens instead?

What actually happens is the element is changed when the browser hits 800px, rather than 640px.

...

## Possible Solution

If you place the custom breakpoint at the end of the list, then the problem goes away.

so you can do the following

```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
  newbreakpoint: 800px
);
```

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

Explained above ^

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2020-01-11 17:52
> If you place the custom breakpoint at the end of the list, then the problem goes away.

That is correct and expected as we use nth- helper methods in the scss code to generate the css from the list.
Normally a custom name in the middle makes not much sense as we already have good default names.

**Comment by DanielRuf** [comment] 2020-01-11 17:55
https://github.com/foundation/foundation-sites/blob/develop/scss/util/_breakpoint.scss

It is not a bug but it's not documented.

Do you want to provide a PR for the docs?

**Comment by DanielRuf** [comment] 2020-01-29 06:41
Closing as we did not receive further feedback.

**Closed by DanielRuf** 2020-01-29 06:41 UTC
Labels: scss
