### ISSUE TITLE
This is now hosted at https://download.get.foundation/sites/download/

### ISSUE THREAD

**Issue by JonathanRimmer** [foundation/foundation-sites#12212] opened 2021-03-16 09:32 UTC
I have been trying to access the CSS custom download page of the foundation site for a few months now and it appears to be down I get the following message: 
This account has been disabled. Please visit https://uberspace.de/support.
Dieser Account wurde deaktiviert. Bitte besuche https://uberspace.de/support.

Is there an issue with the site or has this page been taken down? Its was suggested I highlight this issue with  @joeworkman

Many thanks

**Comment by alexkuc** [comment] 2021-03-17 11:17
I think this issue should be closed as it is a duplicate of https://github.com/foundation/foundation-sites/issues/12211

**Comment by JonathanRimmer** [comment] 2021-03-17 11:34
That issue was closed so I thought it needed a new ticket to flag as a new issue as the page is coming back with the message I mentioned above

**Comment by alexkuc** [comment] 2021-03-17 12:54
I think it would help to indicate that this is a *new* problem because on the surface it looks like a duplicate issue

**Comment by DanielRuf** [comment] 2021-03-21 16:57
Please see https://github.com/foundation/foundation-sites/issues/12189 and the relevant comments.

**Comment by DanielRuf** [comment] 2021-03-21 16:58
https://github.com/foundation/foundation-sites/issues/12189#issuecomment-753378198

**Closed by DanielRuf** 2021-03-21 16:57 UTC
