### ISSUE TITLE
xy-cell-breakpoints is documented, but doesn't exist

### ISSUE THREAD

**Issue by apriljunge** [foundation/foundation-sites#12127] opened 2020-08-14 22:01 UTC
## Description

This is not a new issue. This was reported in #10276 and #10643 (duplicate) and already resolved in #10834.
Somehow it [came back in the docs](https://github.com/foundation/foundation-sites/blame/develop/docs/pages/xy-grid.md#L483-L490). I can't figure out why. Is there a reason?

## Possible Solution

Delete it again.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

If this is not intentional I'd open a PR for this.

**Comment by DanielRuf** [comment] 2020-08-14 22:26
It looks like https://github.com/foundation/foundation-sites/commit/1d910376bab4f142df09245bdf6667e74653fec7#diff-ce995d0e73230b3c0bebc3ff7498d9d6 was the cause as the branches were recreated by @joeworkman afaik and some commits may have been lost.

**Comment by DanielRuf** [comment] 2020-08-14 22:27
It looks like https://github.com/foundation/foundation-sites/commit/1d910376bab4f142df09245bdf6667e74653fec7#diff-ce995d0e73230b3c0bebc3ff7498d9d6 was the cause as the branches were recreated by @joeworkman afaik and some commits / changes may have been lost in the process of resolving the conflicts.

**Closed** 2020-08-15 12:24 UTC
Labels: XY Grid, 📖 documentation
