### ISSUE TITLE
[Abide] Foundation 6.6 Form doesn't submit if button type and name are both "submit"

### ISSUE THREAD

**Issue by amygilbert** [foundation/foundation-sites#11935] opened 2019-12-11 18:33 UTC
## What should happen?
Form using Abide plugin should submit when submit button is pressed. type="submit" and name="submit" should be allowed
...

## What happens instead?
If both type="submit" and name="submit" are coded on the button element, the form does not submit
...

## Possible Solution

Work around it by not coding either type="submit" or name="submit". Since button inside form does not require coding type="submit" that should be no problem.

I don't believe this behavior is standard so I wanted to report the issue.
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case:
Foundation 6.5.3: https://codepen.io/amygilbert/pen/oNgxOjz
Foundation 6.6: https://codepen.io/amygilbert/pen/XWJdQpJ

No fields are required: just hit submit to test

How to reproduce:
See above

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.3 and 6.6
- Browser(s) name and version(s): Google Chrome Version 79.0.3945.79 (Official Build) (64-bit) and Firefox Version 71.0 (64-bit)
- Device, Operating System and version: Windows 10 Pro version 1909
- Link to your project: https://phoenixsoftware.com/

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2019-12-11 19:29
Seems we have to adjust https://github.com/foundation/foundation-sites/blob/develop/js/foundation.abide.js#L37 and https://github.com/foundation/foundation-sites/blob/develop/js/foundation.abide.js#L40

**Comment by DanielRuf** [comment] 2019-12-11 19:32
Hi @amygilbert,

Good catch! Thanks for reporting this.

It seems we have to adjust https://github.com/foundation/foundation-sites/blob/develop/js/foundation.abide.js#L37 and https://github.com/foundation/foundation-sites/blob/develop/js/foundation.abide.js#L40

**Comment by amygilbert** [comment] 2019-12-11 20:29
Hi @DanielRuf, 

Glad to help. And thanks for all your hard work!

Amy

**Comment by DanielRuf** [comment] 2019-12-11 22:42
Hi @amygilbert,

currently I can not understand the exact issue.

When I define abide rules both buttons work:
https://codepen.io/DanielRuf/pen/mdyEyEB

The `name`attribute is never used and so there should not be any problem.

**Comment by DanielRuf** [comment] 2019-12-11 22:47
Can you clarify your issue and provide a reproducible testcase as codepen? Currently the two codepens do not have any abide rules and simply submit the form (open a new page with google.com).

**Comment by amygilbert** [comment] 2019-12-11 23:40
Your codepen is using 6.5.3 which doesn't have the problem. I should have clarified. My first test case was to show it working properly in 6.5.3. My second codepen demonstrates the problem introduced in 6.6. I edited my test case for 6.6 just (https://codepen.io/amygilbert/pen/XWJdQpJ) to include a couple of required fields and still have the problem. Click the submit button and nothing happens.

**Comment by DanielRuf** [comment] 2019-12-12 06:13
Thanks for the clarification. I can reproduce it on https://codepen.io/DanielRuf/pen/LYEZNvM

I will check that 9in detail later. Not sure if it is a conflict with jQuery in general.

It seems we also have a regression there regarding required fields:
<img width="535" alt="Bildschirmfoto 2019-12-12 um 07 10 05" src="https://user-images.githubusercontent.com/827205/70687119-7ae5f700-1cae-11ea-8607-5fe34f0b109a.png">

**Comment by DanielRuf** [comment] 2019-12-12 06:13
Thanks for the clarification. I can reproduce it on https://codepen.io/DanielRuf/pen/LYEZNvM

I will check that in detail later. Not sure if it is a conflict with jQuery in general.

It seems we also have a regression there regarding required fields:
<img width="535" alt="Bildschirmfoto 2019-12-12 um 07 10 05" src="https://user-images.githubusercontent.com/827205/70687119-7ae5f700-1cae-11ea-8607-5fe34f0b109a.png">

**Comment by DanielRuf** [comment] 2019-12-12 09:24
It is caused by 20ba5ff2dea43f055c670629f63227569b94ec5c, not yet sure why.

**Comment by DanielRuf** [comment] 2019-12-12 10:23
Ah, as expected it is a bug with jQuery. See https://bugs.jquery.com/ticket/4652#comment:14

This is caused by https://github.com/foundation/foundation-sites/blob/develop/js/foundation.abide.js#L71.

And see https://api.jquery.com/submit/

> Additional Notes:
> * As the .submit() method is just a shorthand for .on( "submit", handler ), detaching is possible using .off( "submit" ).
> * Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures. For a complete list of rules and to check your markup for these problems, see DOMLint.

I think we can close this as wontfix as even `.trigger('submit')` will not fix this.

**Closed** 2019-12-12 10:23 UTC
Labels: Abide, close:won't fix, javascript

**Comment by amygilbert** [comment] 2019-12-12 13:42
Yes, that's it. Thanks for looking into this and good to know about not using the name or id "submit"

**Comment by joeworkman** [comment] 2020-01-31 00:16
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/submit-button-not-working/902/3

**Comment by joeworkman** [comment] 2020-02-05 06:20
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/submit-button-not-working/902/14

**Comment by alexkuc** [comment] 2021-04-19 17:14
@DanielRuf I am not able to find this in the current [docs](https://get.foundation/sites/docs/abide.html). Is this a regression?

**Comment by DanielRuf** [comment] 2021-04-19 17:42
@alexkuc

I'm not 100% sure but it is a conflict with jQuery.
https://github.com/foundation/foundation-sites/issues/11935#issuecomment-564944846

**Comment by DanielRuf** [comment] 2021-04-19 17:42
@alexkuc

I'm not 100% sure but it seems to be a conflict with jQuery.
https://github.com/foundation/foundation-sites/issues/11935#issuecomment-564944846

**Comment by alexkuc** [comment] 2021-04-19 17:43
@DanielRuf there is a PR #11994 to update docs to reflect this but for some reason it is no longer there?

**Comment by DanielRuf** [comment] 2021-04-19 17:49
https://github.com/foundation/foundation-sites/commits/develop/docs/pages/button.md

Are you sure?
https://get.foundation/sites/docs/button.html

<img width="827" alt="Bildschirmfoto 2021-04-19 um 19 49 25" src="https://user-images.githubusercontent.com/827205/115280582-650cff80-a148-11eb-8b60-0f5dfaa14b6e.png">

**Comment by alexkuc** [comment] 2021-04-20 16:26
It appears that the Abide section of the docs does not include this information. I think it would be very useful to have that information there as well (maybe even verbatim). I can create a PR for this if you think this is the right way to go.

**Comment by alexkuc** [comment] 2021-06-06 19:19
@DanielRuf PR created, let me know what you think
