### ISSUE TITLE
Responsive Accordion Tab throws error when using data-match-height

### ISSUE THREAD

**Issue by alexanderjakob** [foundation/foundation-sites#12106] opened 2020-07-06 11:20 UTC
We are using Responsive Accordion Tabs in our project. The match-height option is used as a data-attribute. By resizing the browser and changing from accordion state to tabs state theres an error thrown.

![Bildschirmfoto 2020-07-06 um 13 18 58](https://user-images.githubusercontent.com/9250626/86588108-57a4d100-bf8b-11ea-9940-c665051db819.jpg)

## What should happen?
The accordion state should be initialized after resizing without throwing an error.

## What happens instead?
The accordion state throws an error by resizing from accordion to tab state and back again.

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: https://codepen.io/IamManchanda/pen/eWKPqE

How to reproduce:
1. Open test case
2. Add data-match-height="true" to data-responsive-accordion-tabs-Element
3. Resize multiple times and watch console

## Context
We are trying to have tabs with matching heights after resizing.

## Your Environment
- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): every browser
- no link due to internal environment

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment] 2020-07-06 11:33
Hi @alexanderjakob,

thanks for reporting this. Please provide a reproducible testcase as codepen.

**Comment by alexanderjakob** [comment] 2020-07-06 12:28
https://codepen.io/alexanderjakob/pen/YzweMoQ

Here you go, just resize and have a look into your console

**Comment by DanielRuf** [comment] 2020-07-06 12:37
I can see only this error:

![grafik](https://user-images.githubusercontent.com/827205/86593809-37c6da80-bf96-11ea-9ba4-d063730ef75c.png)

**Comment by DanielRuf** [comment] 2020-07-06 12:38
It seems you used `https://codepen.io/ZURBFoundation/pen/jmYLwq`. I will fork the codepen and use the latest Foundation version.

**Comment by DanielRuf** [comment] 2020-07-06 12:40
It seems you used `https://codepen.io/ZURBFoundation/pen/jmYLwq`. I will fork the codepen and use the latest Foundation version.

Same error in Firefox (`this.$tabContent is null`)`: https://codepen.io/DanielRuf/pen/rNxJgxO

**Comment by alexanderjakob** [comment] 2020-07-06 15:11
my reported error was in chrome, sorry for inaccuracy

**Comment by DanielRuf** [comment] 2020-07-06 15:34
Can you test with my link and post the error from there? Also please test in an incognito window and check which line from foundation.js throws this error. I am currently not on a computer.

**Comment by alexanderjakob** [comment] 2020-07-08 10:22
I have the same issue with your link, see attached file for line number.

![Bildschirmfoto 2020-07-08 um 12 21 11](https://user-images.githubusercontent.com/9250626/86907615-9b2b4680-c115-11ea-96a2-ca323aa1cd9c.jpg)

**Comment by DanielRuf** [comment] 2020-07-08 12:37
```
this.$tabContent
      .find(`.${this.options.panelClass}`)
```

It looks like tabContent is not defined. I have not that much time to debug this in detail. Maybe there is something missing in the markup or not correct.

**Comment by alexanderjakob** [comment] 2020-07-09 08:09
Ähm. This is an example from Foundation's website - when there's something missing, how should I know? I think that changing from accordion to tabs and back again breaks the behavior of this component. Resizing removes classes and so on ...

**Comment by DanielRuf** [comment] 2020-07-09 08:21
Sure, we maybe forgot to update the docs. That's why I said we have to debug this in detail.

**Comment by apriljunge** [comment] 2020-08-20 07:57
I digged a little bit into the Code and I can assure now that this isn't an issue with markup :smile:

It happens when the tabs are transferred to the accordion (large to small screens). The method [`_setHeight`](https://github.com/foundation/foundation-sites/blob/develop/js/foundation.tabs.js#L384) of tabs is still trying to perform operations on the `$tabContent`. But this element is already gone, as it's an accordion now.

When resizing to small screens `changed.zf.mediaquery` triggers two things relevant in this case:
1. Destroying the tabs
2. Checking height in tabs (_setHeight)

Even though the [destroying of tabs unbinds the `_setHeight` method](https://github.com/foundation/foundation-sites/blob/develop/js/foundation.tabs.js#L418-L429), it triggers this one time. Because it's a little bit complicated to describe, please have a look into this jQuery Snippet.

```
let setHeight = () =>  {
  console.log('set Height');
}

let destroyTabs = () => {
  console.log('Tabs destroyed');
  $(window).off('resizeEvent', setHeight);
}

$(window).on('resizeEvent', destroyTabs);
$(window).on('resizeEvent', setHeight);

$(window).trigger('resizeEvent');

/* setHeight AND destroyTabs are both executed */
```

**Closed** 2020-09-04 21:38 UTC
Labels: Responsive Accordion Tabs, javascript
