### ISSUE TITLE
[Installation] Download link not working on site

### ISSUE THREAD

**Issue by jacoor** [foundation/foundation-sites#12240] opened 2021-07-14 06:52 UTC
https://get.foundation/sites/docs/installation.html
There is a section: https://get.foundation/sites/docs/installation.html#download - the link is dead. Please fix.

**Comment by DanielRuf** [comment] 2021-07-25 16:44
Duplicate of this pinned issue: https://github.com/foundation/foundation-sites/issues/12189

**Closed by DanielRuf** 2021-07-25 16:44 UTC
