### ISSUE TITLE
Different css versions of 6.6.3 with different download links – one doesn't work for me

### ISSUE THREAD

**Issue by reinhardmohr** [foundation/foundation-sites#12100] opened 2020-06-22 12:36 UTC
## Expected Behavior

As a non-developer I need the css version as a starter. When I‘m on 
https://get.foundation
and click the download button I get "Foundation-Sites-6.6.3-CSS.zip" from https://static.download.foundation/sites-css-latest that at least I couldn't get to work properly. 
Obviously javascript doesn't work properly; but I had no time to dive into it so I used an older 6.6.1 version that worked for me.
Today I tried it  the "Download-Everything-Button" on
https://download.get.foundation/sites/download/
and got "foundation-6.6.3-complete.zip". 
There is a different html-starter-template (links to js are different and 4 instead of only 2) that might work.
...

## Current Behavior

https://get.foundation
provides a non-working starter template (at least for me)

https://download.get.foundation/sites/download/
downloads to me another starter template wth the same version number 6.6.3 in the css

...

## Possible Solution

make both download links download the same working css version
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. download on https://get.foundation
2. download on https://download.get.foundation/sites/download/
3. compare, use only one working download file

## Context

...

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): Safari on Mac
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

THANKS FOR HELPING

**Comment by DanielRuf** [comment] 2020-06-22 15:03
The static download was just a workaround since I host the customizer.
What exactly does not work with Foundation-Sites-6.6.3-CSS.zip?
Can you provide a reproducible testcase as repository?

**Comment by reinhardmohr** [comment] 2020-06-23 13:03
Hi, Daniel,
thank you for offering help. I am not really a developer so I cannot easily provide a codepen or something alike.
What I did to clarify things:

1. I downloaded both css versions of Foundation 6.6.3.
2. Then I copied the code for a dropdown menu from the official documentation (https://get.foundation/sites/docs/dropdown-menu.html – from the "Edit in Browser" page).
3. And pasted this code into the two seemingly identical starter templates.
4. Then I uploaded both downloaded starter folders (only removed the dots between the numbers to my server).

a) The template downloaded from https://get.foundation via the download button is Foundation-Sites-6.6.3-CSS.zip.
Its template can bee seen here:
https://reinhardmohr.de/Foundation-Sites-663-CSS/
The dropdown menu does NOT work.

b) The template downloaded from https://download.get.foundation/sites/download/ via the "get everything button" is foundation-6.6.3-complete.zip.
Its template can bee seen here:
https://reinhardmohr.de/foundation-663-complete/
The dropdown menu DOES work.

The difference between the two templates in the respective downloads (as far as I have noticed):
**for a)**   for Foundation-Sites-6.6.3-CSS.zip the javascript is called with two lines:
<script src="assets/js/vendor.js"></script>
<script src="assets/js/foundation.js"></script>

**for b)**   for foundation-6.6.3-complete.zip the javascript is called with four lines:
    <script src="js/vendor/jquery.js"></script>
    <script src="js/vendor/what-input.js"></script>
    <script src="js/vendor/foundation.js"></script>
    <script src="js/app.js"></script>

I hope this helps. If you need more information: Please let me know I try to provide it.

Thanks for your support (for Foundation and for the people asking for help)!

Reinhard

**Comment by DanielRuf** [comment] 2020-06-23 13:46
Running `$(document).foundation()` should resolve this (which is in the other one in app.js) as Foundation Sites will not initialize the components just by loading the js file:

![grafik](https://user-images.githubusercontent.com/827205/85411429-a3598280-b568-11ea-878a-d8b37ef50aeb.png)

![grafik](https://user-images.githubusercontent.com/827205/85411441-a94f6380-b568-11ea-8aeb-13f138e7d000.png)

**Comment by reinhardmohr** [comment] 2020-06-26 10:03
Hi, Daniel,
thanks a lot for helping! This solved my problem – the dropdown menu in the css starter template now works!

I added a third line of code in the template at the bottom right after the two lines that call the external javascript files.
Now it is:
`<script src="assets/js/vendor.js"></script>`
`<script src="assets/js/foundation.js"></script>`
`<script>$(document).foundation()</script>`
After reloading the page and clearing the browser cache everything works!
Thanks a lot for helping – and for making and supporting Foundation!
It's such an enormous help in my everyday worklife that I can work with this great framework!

Thanks
Reinhard

**Comment by DanielRuf** [comment] 2020-06-26 13:34
Great to hear that it works for you now. Closing as resolved.

**Closed by DanielRuf** 2020-06-26 13:34 UTC
Labels: question
