### ISSUE TITLE
Custom Build Download is Not Working

### ISSUE THREAD

**Issue by hecforce** [foundation/foundation-sites#12197] opened 2021-01-28 17:33 UTC
I was surprised to see that this link is dead. Will this dead link be resolved? If so, when?
**Dead Link:** https://download.get.foundation/sites/download

Thanks,

**Comment by DanielRuf** [comment] 2021-01-28 20:30
Closing as duplicate of https://github.com/foundation/foundation-sites/issues/12189

Please check the open and pinned issues and use the search before opening new issues. Thank you.

**Closed by DanielRuf** 2021-01-28 20:30 UTC

**Comment by hecforce** [comment] 2021-01-28 21:01
Thanks Daniel, 

I did search but apparently missed the pin. It would be nice to have that page up and running again. At least there is a work around. I appreciate it.
